### ISSUE TITLE
change the default textarea height 

### ISSUE THREAD

**Issue by YuYanzy** [andrerpena/react-mde#306]
Is there any possible way to change the default textarea height?
I have tried directly adding the css code but not work.

``` css
.mde-textarea-wrapper textarea.mde-text {
    width: 100%;
    height: 80%;  //Add line 
    border: 0;
    padding: 10px;
    vertical-align: top;
    resize: vertical;
    overflow-y: auto;
}

```
